#ifndef HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_
#define HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_

#include "DIO_Interface.h"

#define DC_MOTOR_INPUT1_PORT DIO_PORTC
#define DC_MOTOR_INPUT2_PORT DIO_PORTC

#define DC_MOTOR_INPUT1_PIN  PIN2
#define DC_MOTOR_INPUT2_PIN  PIN7


#endif /* HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_ */
