
#ifndef MCAL_TIMER0_TIMER0_CONFIG_H_
#define MCAL_TIMER0_TIMER0_CONFIG_H_

#include "Timer0_Private.h"

/*
 * choose from:
 *   TIMER0_PRESCALER_1
 *   TIMER0_PRESCALER_8
 *   TIMER0_PRESCALER_64
 *   TIMER0_PRESCALER_256
 *   TIMER0_PRESCALER_1024
 *   TIMER0_PRESCALER_EXTCLK_FALLEDGE
 *   TIMER0_PRESCALER_EXTCLK_RAISEDGE
 */
#define TIMER_0_PRESCALER     TIMER0_PRESCALER_1024

/*
 *   choose from :
 *   TIMER0_NORMAL_MODE
 *   TIMER0_CTC_MODE
 *   TIMER0_PHASECORRECT_MODE
 *   TIMER0_FASTPWM_MODE
 */
#define TIMER_0_MODE  TIMER0_FASTPWM_MODE

/*
 * choose from :
 *  Non PWM:
 *   TIMER0_OC0_DISCONNECTED
 *   TIMER0_OC0_TOGGLE
 *   TIMER0_OC0_CLEAR
 *   TIMER0_OC0_SET
 *  PWM:
 *   TIMER0_OC0_PWM_NON_INVERTING
 *   TIMER0_OC0_PWM_INVERTING
 */
#define TIMER_0_OC0_MODE  TIMER0_OC0_PWM_NON_INVERTING

#define F_SYS 8000000

#endif /* MCAL_TIMER0_TIMER0_CONFIG_H_ */
