/*
 * Timer0_Config.h
 *
 *  Created on: Sep 28, 2023
 *      Author: amrel
 */

#ifndef NASR_60_EMBEDDED_RESOURCES_AVR_DRIVERS_MCAL_TIMER0_TIMER0_CONFIG_H_
#define NASR_60_EMBEDDED_RESOURCES_AVR_DRIVERS_MCAL_TIMER0_TIMER0_CONFIG_H_

#include "Timer0_Private.h"
/*choose from
  TIMER0_PRESCALER_STOP
  TIMER0_PRESCALER_1
  TIMER0_PRESCALER_8
  TIMER0_PRESCALER_64
  TIMER0_PRESCALER_256
  TIMER0_PRESCALER_1024
 */
#define TIMER0_PRESCALER      TIMER0_PRESCALER_1024

/*choose from :
  TIMER0_MODE_NORMAL
  TIMER0_MODE_CTC
*/
#define TIMER0_MODE           TIMER0_MODE_NORMAL

/* enter the set frequency of your AVR*/
#define SYS_FREQ             800000000


#endif /* NASR_60_EMBEDDED_RESOURCES_AVR_DRIVERS_MCAL_TIMER0_TIMER0_CONFIG_H_ */
