
#ifndef HAL_SEVENSEG_SEVENSEG_CONFIG_H_
#define HAL_SEVENSEG_SEVENSEG_CONFIG_H_

#define SEVENSEG_DISPLAY_PORT DIO_PORTA
#define SEVENSEG_DISPLAY_SHIFT 4

#define SEVENSEG1_EN_PORT DIO_PORTB
#define SEVENSEG1_EN_PIN PIN1

#define SEVENSEG2_EN_PORT DIO_PORTB
#define SEVENSEG2_EN_PIN PIN2
#endif /* HAL_SEVENSEG_SEVENSEG_CONFIG_H_ */
