
#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_

#include "ADC_Private.h"

/* SELECT AREF MODE: AVCC, AREF_PIN,_2V56 */
#define ADC_V_REF	AVCC

/* SELECT ADC_CHANNEL: ADC0 -> ADC7 */
#define ADC_CHANNEL ADC1

/* SELECT ADC_PRESCALER: _2_DIVISION_FACTOR -> _128_DIVISION_FACTOR */
#define ADC_PRESCALER _64_DIVISION_FACTOR

#endif /* MCAL_ADC_ADC_CONFIG_H_ */
